package com.soul.itr.tax.utils;

public enum Form16Constants {
	CONVEYANCE_ALLOWANCE,
	MEDICAL_ALLOWANCE,
	PROFESSIONAL_TAX,
	HRA,
	TOTAL_INCOME,
	BASIC_SALARY,
	MONTHLY_RENT,
	EDU_LOAN_80C,
	PPF_80C,
	LIC_80C,
	NSC_80C,
	PF_80C,
	HOME_LOAN_PRINCIPLE_80C,
	HOME_STAMP_DUTY_80C,
	HOME_LOAN_INTERESET_80C,
	CHARITY,
	TAXABLE_INCOME,
	TOTAL_TAX,
	TAX_DEDUCTED
}
